import numpy as np
import copy
import sys
import os
from typing import Union, List, Tuple, Dict, Any, Optional
from opto.features.priority_search.search_template import Samples, SearchTemplate, BatchRollout
from opto.features.priority_search.regressor import LogisticRegressor, LinearRegressor, LinearUCBRegressor, LLMRegressor
# import pretrained regressors
from my_processing_agents.pretained_regressor import PretrainedLinearRegressor, PretrainedLogisticRegressor
from opto.optimizers.utils import print_color
from opto.trainer.utils import safe_mean
from opto.features.priority_search.priority_search import PrioritySearch, ModuleCandidate, HeapMemory
from opto.features.priority_search.priority_search_with_regressor import PrioritySearch_with_Regressor
from opto.trainer.utils import async_run
from opto.features.priority_search.utils import remap_update_dict
from opto.trainer.algorithms.basic_algorithms import batchify
class PS_Children_Score(PrioritySearch_with_Regressor):
    """
    Keep track of children's mean score.
    
    This class extends PrioritySearch_with_Regressor to track parent-child relationships
    between candidates. When new candidates are proposed from existing exploration candidates,
    they are added as children to their parent candidates. This allows for analysis of
    how successful different exploration strategies are at generating good offspring.
    """

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        
    
    def train(self, *args, **kwargs):
        """ Train the agent. """
        super().train(*args, **kwargs)
        self.plot_parent_children_scores()
        return

    def plot_parent_children_scores(self):
        """ Plot figures """
        import matplotlib.pyplot as plt
        import numpy as np
        
        # First plot: actual mean scores
        # get the mean score of the children and the parent
        parent_children_scores = []
        for _ , candidate in self.long_term_memory.memory+self.short_term_memory.memory:
            parent_score = candidate.mean_score()
            children_score = candidate.children_mean_score()
            if parent_score is not None and children_score is not None:
                parent_children_scores.append((parent_score, children_score))
        parent_children_scores = np.array(parent_children_scores)
        
        # Create first figure for actual scores
        plt.figure(figsize=(8, 6))
        plt.scatter(parent_children_scores[:, 0], parent_children_scores[:, 1])
        plt.xlabel('Parent Mean Score')
        plt.ylabel('Children Mean Score')
        plt.title('Actual Parent vs Children Mean Scores')
        plt.grid(True, alpha=0.3)
        plt.savefig('parent_children_scores.png', dpi=300, bbox_inches='tight')
        plt.close()  # Close the figure to free memory
        
        # Second plot: predicted scores
        predicted_parent_children_scores = []
        for _ , candidate in self.long_term_memory.memory+self.short_term_memory.memory:
            parent_score = candidate.predicted_score
            children_score = candidate.predicted_children_score
            assert parent_score is not None and children_score is not None, "Parent and children predicted scores must be not None"
            predicted_parent_children_scores.append((parent_score, children_score))
        predicted_parent_children_scores = np.array(predicted_parent_children_scores)
        
        # Create second figure for predicted scores
        plt.figure(figsize=(8, 6))
        plt.scatter(predicted_parent_children_scores[:, 0], predicted_parent_children_scores[:, 1])
        plt.xlabel('Parent Predicted Score')
        plt.ylabel('Children Predicted Score')
        plt.title('Predicted Parent vs Children Scores')
        plt.grid(True, alpha=0.3)
        plt.savefig('predicted_parent_children_scores.png', dpi=300, bbox_inches='tight')
        plt.close()  # Close the figure to free memory
        
        # save two data to numpy arrays
        np.save('parent_children_scores.npy', parent_children_scores)
        np.save('predicted_parent_children_scores.npy', predicted_parent_children_scores)
        
        print(f"Plots saved: parent_children_scores.png and predicted_parent_children_scores.png")
        print(f"Data saved: parent_children_scores.npy and predicted_parent_children_scores.npy")

    def propose(self,
                samples : Samples,
                verbose : bool = False,
                **kwargs):
        """ Analyzing samples and propose new parameters using self.optimizer. An independent optimizer is used for the minibatch generated by one agent and generates n_proposals proposals.

        Args:
            samples (Samples): Samples collected by the exploration candidates. If None, the agent's parameters are returned without updating.
            verbose (bool, optional): Whether to print verbose output. Defaults to False.
            **kwargs: Additional keyword arguments that may be used by the implementation.

        Returns:
            candidates (list of ModuleCandidate): A list of proposed candidates for the next iteration.
        """
        print("--- Proposing new parameters...") if verbose else None
        assert isinstance(samples, Samples), "samples must be an instance of Samples."
        samples = samples.samples  # list of BatchRollout objects
        n_proposals = self.num_proposals  # number of proposals to generate per optimizer

        # Associate each BatchRollout with self._exploration_candidates
        matched_candidates_and_samples = self.match_candidates_and_samples(self._exploration_candidates, samples)
        # NOTE len(matched_candidates_and_samples) <= len(self._exploration_candidates) since some exploration candidates might be duplicated.
        candidate_batchrollouts_list = [ (k,b) for k, v in matched_candidates_and_samples.items() for b in v]
        n_batches = len(candidate_batchrollouts_list)  # number of batch rollouts in the samples

        def copy_optimizer(optimizer):
            return copy.deepcopy(optimizer) if self.decouple_optimizers else optimizer

        # need to copy optimizer for the n_batches
        def _backward(n):
            candidate, rollouts = candidate_batchrollouts_list[n]
            optimizer = candidate.optimizer or self.optimizer
            # Create a copy of the optimizer to avoid modifying the original one and to allow parallel execution
            optimizer = copy_optimizer(optimizer)
            optimizer.parameters = rollouts.module.parameters()  # set the optimizer's parameters to the proposal's parameters
            targets = [r.target for r in rollouts]
            feedbacks = [r.feedback for r in rollouts]
            # batchify the targets and feedbacks
            target = batchify(*targets)
            feedback = batchify(*feedbacks).data  # str
            # standard optimizer step
            optimizer.zero_feedback()  # reset the optimizer's feedback
            optimizer.backward(target, feedback)  # compute the gradients based on the targets and feedbacks
            return optimizer

        args_list = [(n,) for n in range(n_batches)]
        optimizers = async_run([_backward]*n_batches,  # run the optimizer step for each agent in parallel
                                 args_list=args_list,
                                 max_workers=self.num_threads,  # use the number of threads specified in the class
                                 description='Backward')
        assert len(optimizers) == n_batches, "Number of optimizers must match number of batch rollouts."
        # need to copy optimizer for the n_proposals
        # NOTE when optimizer is deepcopied, its parameters are not copied.
        optimizers = [copy_optimizer(o) for o in optimizers ] * n_proposals  # repeat args_list n_proposals times
        assert len(optimizers) == n_batches * n_proposals, "Number of optimizers must match number of batch rollouts times number of proposals."

        # For each optimizer, containing the backward feedback, we call it n_proposals times to get the proposed parameters.
        def _step(n):
            optimizer = optimizers[n]
            update_dict = optimizer.step(verbose=verbose, num_threads=self.num_threads, bypassing=True, **kwargs)
            if not update_dict:  # if the optimizer did not propose any updates
                return None # return None to indicate no updates were proposed
            # update_dict may only contain some of the parameters of the agent, we need to make sure it contains all the parameters
            # since the current agent might have different parameters than the one used by the optimizer
            for param in optimizer.parameters: # for all parameters
                if param not in update_dict: # update_dict misses some parameters
                    update_dict[param] = param.data # add the parameter to the update_dict
            # the update_dict is linked to the copied parameters of the agent, we set it back to the agent's parameters
            update_dict = remap_update_dict(self.agent, update_dict)  # remap the update dict to the agent's parameters
            return update_dict  # return the proposed parameters

        args_list = [(n,) for n in range(n_batches*n_proposals)]
        update_dicts = async_run([_step]*n_batches*n_proposals,  # run the optimizer step for each agent in parallel
                                  args_list=args_list,
                                  max_workers=self.num_threads,  # use the number of threads specified in the class
                                  description=f"Calling optimizers: Generating {n_proposals} proposals for each of {n_batches} batches",)

        # Clear the optimizers to avoid memory leaks
        for optimizer in optimizers:
            optimizer.zero_feedback()  # reset the optimizer's feedback
            optimizer.parameters = []  # clear the optimizer's parameters to avoid memory leaks

        # update_dicts is a list of dicts of length n_batches * n_proposals
        # Create ModuleCandidate objects for each proposed update_dict that is non-trivial
        # Also track parent-child relationships
        candidates = []
        
        # Track which parent candidate each new candidate comes from
        for i, (update_dict, optimizer) in enumerate(zip(update_dicts, optimizers)):
            if update_dict is not None:
                # Create the new candidate
                new_candidate = ModuleCandidate(self.agent, update_dict, optimizer)
                
                # Find the parent candidate that generated this new candidate
                # The optimizers list is structured as: [opt_0, opt_1, ..., opt_{n_batches-1}] repeated n_proposals times
                # So update_dicts[i] corresponds to candidate_batchrollouts_list[i % n_batches]
                parent_batch_idx = i % n_batches
                parent_candidate, _ = candidate_batchrollouts_list[parent_batch_idx]
                
                # Add the new candidate as a child to its parent
                parent_candidate.children.append(new_candidate)
                
                candidates.append(new_candidate)
        
        return candidates
        
    def match_candidates_and_samples(
            self,
            candidates: List[ModuleCandidate],
            samples: List[BatchRollout]):
        """
        Match the given candidates with the provided samples.

        Args:
            candidates (list of ModuleCandidate): A list of ModuleCandidate objects representing the proposed parameters.
            samples (list of BatchRollout): A Samples object containing a list of BatchRollout objects, where each BatchRollout contains rollouts collected by an agent on different inputs.
        Returns:
            results (dict): A dictionary where the keys are ModuleCandidate objects and the values are lists of BatchRollouts collected by the corresponding ModuleCandidate.

        """
        # In general, there may be multiple BatchRollouts collected by the same ModuleCandidate.
        # We group the rollouts by the agent (ModuleCandidate) and return a dictionary
        # where the keys are the ModuleCandidate objects and the values are Samples

        # Merge children from duplicate candidates before creating _results
        # Since ModuleCandidate has __hash__ and __eq__, duplicates will be merged when used as dict keys
        candidate_to_children = {}  # Track all children for each unique candidate
        
        # First pass: collect all children for each unique candidate
        for candidate in candidates:
            if candidate not in candidate_to_children:
                candidate_to_children[candidate] = []
            candidate_to_children[candidate].extend(candidate.children)
        
        # Merge children into the representative candidates
        for candidate, all_children in candidate_to_children.items():
            candidate.children = all_children
        
        # Now create _results with unique candidates (duplicates automatically merged)
        _results = { c: [] for c in candidate_to_children.keys()}  # dict of ModuleCandidate: list of BatchRollouts
        ids = {id(c): c for c in candidates}  # dict of ModuleCandidate id: ModuleCandidate

        for rollouts in samples:
            assert isinstance(rollouts, BatchRollout), "Each element in samples must be a BatchRollout object."
            # rollouts is a BatchRollout object
            module = rollouts.module  # trace.Module
            key = getattr(module, '__TRACE_RESERVED_module_candidate_id')  # use the candidate as the key
            if key not in ids:
                raise ValueError(f"ModuleCandidate with id {key} not found in results. Samples are not collected by known candidates.")
            # Append the rollouts to the list of rollouts for the key
            _results[ids[key]].append(rollouts)

        if self._enforce_using_data_collecting_candidates:
            # assert all candidates have at least one rollout
            for c in candidates:
                assert len(_results[c]) > 0, f"ModuleCandidate with id {id(c)} has no rollouts. Samples are not collected by known candidates."

        assert len(samples) == sum(len(rollouts) for rollouts in _results.values()), "All samples must be associated with exploration candidates."
        # print(f"Number of candidates in matched_candidates_and_samples: {len(_results)}")
        # breakpoint()
        return _results

    
    def print_memory_stats(self):
        # For debugging, print all candidates: number, mean_score(), num_rollouts, predicted_score. It is better to see an increasing trend in the predicted scores.
        print("--- Printing memory stats...")
        # # print statistics of the base agent
        # base_candidate = self.base_agent_ModuleCandidate
        # mean_score = base_candidate.mean_score()
        # mean_score_str = f"{mean_score:.4g}" if mean_score is not None else "None"
        # print_color(f"Base agent, Mean Score: {mean_score_str}, Num Rollouts: {base_candidate.num_rollouts}, Predicted Score: {base_candidate.predicted_score}", "magenta")
        # print_color(f"Number of children: {len(base_candidate.children)}, Children rollouts: {base_candidate.children_num_rollouts()}, Children Mean Score: {base_candidate.children_mean_score()}", "magenta")
        print("Long-term memory:")
        # If len(self.long_term_memory.memory)>40, only print the first 20 and the last 20 candidates
        for i, (_, candidate) in enumerate(self.long_term_memory.memory):
            # if len(self.long_term_memory.memory) <= 40 or i < 20 or i >= len(self.long_term_memory.memory) - 20:
                mean_score = candidate.mean_score()
                mean_score_str = f"{mean_score:.4g}" if mean_score is not None else "None"
                print_color(f"Candidate {i}, Mean Score: {mean_score_str}, Num Rollouts: {candidate.num_rollouts}, Predicted Score: {candidate.predicted_score}", "magenta")
                print_color(f"Number of children: {len(candidate.children)}, Children rollouts: {candidate.children_num_rollouts()}, Children Mean Score: {candidate.children_mean_score()}, Children Predicted Score: {candidate.predicted_children_score}", "green")
    
